
compile:
	mvn compile

run:
	mvn compile exec:java -Dexec.mainClass="pro.comcon.App"


dsensor_view:
	mvn compile exec:java -Dexec.mainClass="pro.comcon.nui.views.dsensor.SensorExample"



view_lamp:
	mvn compile exec:java -Dexec.mainClass="pro.comcon.nui.views.lamp.LampExample"

