

compile:
	# javac ./src/First.java ./src/ui/*.java -d target/classes
	javac ./src/ui/*.java -d target/classes

# run:
# 	java -cp target/classes/ First

status_panel_example:
	java -cp target/classes/ ui.StatusPanelExample

main_window:
	java -cp target/classes/ ui.MainWindow