
compile:
	mvn compile

run:
	mvn compile exec:java -Dexec.mainClass="pro.nia.jdocker.App"

main_window:
	mvn compile exec:java -Dexec.mainClass="pro.nia.jdocker.ui.MainWindow"

images_page:
	mvn compile exec:java -Dexec.mainClass="pro.nia.jdocker.ui.pages.images.ImagesPageExample"